apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c7u3l5g2e-nodejs
  janus-idp.io/tekton: c7u3l5g2e-nodejs
  backstage.io/kubernetes-id: c7u3l5g2e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c7u3l5g2e-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
