apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c7u3l5g2e-nodejs 
  janus-idp.io/tekton: c7u3l5g2e-nodejs
  backstage.io/kubernetes-id: c7u3l5g2e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c7u3l5g2e-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml